import { createTheme, lightThemePrimitives } from "baseui";

const CondorLightTheme = createTheme(
  {
    // Primitive Values
    ...lightThemePrimitives,

    // Custom Semantic Values (Uncomment and edit as needed)

    primaryFontFamily: "Sora, sans-serif",
    primaryA: "#3D3D3D",
    // primaryB: '...',
    primary: "#1d206a",
    primary50: "#ececb5",
    // primary100: '...',
    // primary200: '...',
    // primary300: '...',
    // primary400: '...',
    // primary500: '...',
    // primary600: '...',
    // primary700: '...',
    // accent: '...',
    // accent50: '...',
    // accent100: '...',
    // accent200: '...',
    // accent300: '...',
    // accent400: '...',
    // accent500: '...',
    // accent600: '...',
    // accent700: '...',
    // negative: '...',
    // negative50: '...',
    // negative100: '...',
    // negative200: '...',
    // negative300: '...',
    // negative400: '...',
    // negative500: '...',
    // negative600: '...',
    // negative700: '...',
    // warning: '...',
    // warning50: '...',
    // warning100: '...',
    // warning200: '...',
    // warning300: '...',
    // warning400: '...',
    // warning500: '...',
    // warning600: '...',
    // warning700: '...',
    // positive: '...',
    // positive50: '...',
    // positive100: '...',
    // positive200: '...',
    // positive300: '...',
    // positive400: '...',
    // positive500: '...',
    // positive600: '...',
    // positive700: '...',
    // mono100: '...',
    // mono200: '...',
    // mono300: '...',
    // mono400: '...',
    // mono500: '...',
    // mono600: '...',
    // mono700: '...',
    // mono800: '...',
    // mono900: '...',
    // mono1000: '...',
    // rating200: '...',
    // rating400: '...',
  },
  {
    // Custom Component Overrides (Uncomment and edit as needed)
    // buttonPrimaryFill: '...',
    // buttonPrimaryText: '...',
    // buttonSecondaryFill: '...',
    // buttonSecondaryText: '...',
    // buttonTertiaryFill: '...',
    // buttonTertiaryText: '...',
    // buttonMinimalFill: '...',
    // buttonMinimalText: '...',
    // buttonDisabledFill: '...',
    // buttonDisabledText: '...',
    // buttonPrimaryActive: '...',
    // buttonPrimaryHover: '...',
    // buttonSecondaryActive: '...',
    // buttonSecondaryHover: '...',
    // buttonTertiaryActive: '...',
    // buttonTertiaryHover: '...',
    // buttonMinimalActive: '...',
    // buttonMinimalHover: '...',
    // buttonDisabledActive: '...',
    // buttonDisabledHover: '...',
    // buttonPrimarySelectedText: '...',
    // buttonPrimarySelectedFill: '...',
    // buttonSecondarySelectedText: '...',
    // buttonSecondarySelectedFill: '...',
    // buttonTertiarySelectedText: '...',
    // buttonTertiarySelectedFill: '...',
    // buttonMinimalSelectedText: '...',
    // buttonMinimalSelectedFill: '...',
    // linkText: '...',
  }
);

export default CondorLightTheme;
